## Numpy

1. Создайте вектор состоящий из чисел от 0 до 11 включительно. 

In [1]:
import numpy as np

vector = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
print (vector)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


2. Измените размерность вектора и превратите его в матрицу 3 х 4

In [2]:
matrix = vector.reshape((3,4))
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


3. Найдите произведение полученной матрицы и вектора [2, 3, 5, 6]

In [3]:
v = np.array([2,3,5,6])
matrix.dot(v)

array([ 31,  95, 159])

4. Из матрицы из пункта 2 сделайте квадратную матрицу состоящую из строк с индексами 0, 1, 3

In [57]:
Matrix = matrix[:2,[1,3]]
print(Matrix)

[[1 3]
 [5 7]]


5. Найдите обратную матрицу к полученной в пункте 4.

In [58]:
Matrix

array([[1, 3],
       [5, 7]])

In [59]:
Matrix_inv= np.linalg.inv(Matrix)

In [63]:
Matrix_inv

array([[-0.875,  0.375],
       [ 0.625, -0.125]])

6. Проверьте является ли она обратной?

In [65]:
Matrix.dot(Matrix_inv)

array([[ 1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00]])

## Pandas

1. Загрузите данные из https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv в DataFrame. Воспользуйтесь одним из способов предложенных на занятии.

In [39]:
pip install wget

Note: you may need to restart the kernel to use updated packages.


In [40]:
import pandas as pd
import wget
wget.download('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv', 'data.csv')

'data (2).csv'

2. Выведите несколько первых строк таблицы. 

In [70]:
data = [
  ['BMW','1 Series M', 2011,'premium unleaded (required)', 335, 6,'MANUAL','rear wheel drive',
    2,'"Factory Tuner,Luxury,High-Performance"','Compact','Coupe', 26, 19, 3916, 46135],
  ['BMW','1 Series',2011,'premium unleaded (required)',300,6,'MANUAL','rear wheel drive',
   2,'"Luxury,Performance"','Compact','Convertible',28,19,3916,40650],
  ['BMW','1 Series',2011,'premium unleaded (required)',300,6,'MANUAL','rear wheel drive',
   2,'"Luxury,High-Performance"','Compact','Coupe',28,20,3916,36350],
  ['Audi', 100, 1992,'regular unleaded','172','6','MANUAL','front wheel drive',
   4,'Luxury','Midsize','Sedan',24,17,3105,2000],
  ['FIAT','124 Spider',2017,'premium unleaded (recommended)',160,4,'MANUAL','rear wheel drive',
   2,'Performance','Compact','Convertible',35,26,819,27495]
]


columns = [
    'Make','Model','Year','Engine Fuel Type','Engine HP','Engine Cylinders','Transmission Type','Driven_Wheels',
    'Number of Doors','Market Category','Vehicle Size','Vehicle Style','highway MPG','city mpg','Popularity','MSRP'
]

In [71]:
pd.DataFrame(data, columns=columns)

Make       Model  Year                Engine Fuel Type Engine HP  \
0   BMW  1 Series M  2011     premium unleaded (required)       335   
1   BMW    1 Series  2011     premium unleaded (required)       300   
2   BMW    1 Series  2011     premium unleaded (required)       300   
3  Audi         100  1992                regular unleaded       172   
4  FIAT  124 Spider  2017  premium unleaded (recommended)       160   

  Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                6            MANUAL   rear wheel drive                2   
1                6            MANUAL   rear wheel drive                2   
2                6            MANUAL   rear wheel drive                2   
3                6            MANUAL  front wheel drive                4   
4                4            MANUAL   rear wheel drive                2   

                           Market Category Vehicle Size Vehicle Style  \
0  "Factory Tuner,Luxury,High-Performance"      Compact         Coupe   
1                     "Luxury,Performance"      Compact   Convertible   
2                "Luxury,High-Performance"      Compact         Coupe   
3                                   Luxury      Midsize         Sedan   
4                              Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           24        17        3105   2000  
4           35        26         819  27495

3. Отфильруйте машины по марке и оставьте только строки с автомобилями BMW. 

In [74]:
df = pd.DataFrame(data, columns=columns)

In [75]:
df

Make       Model  Year                Engine Fuel Type Engine HP  \
0   BMW  1 Series M  2011     premium unleaded (required)       335   
1   BMW    1 Series  2011     premium unleaded (required)       300   
2   BMW    1 Series  2011     premium unleaded (required)       300   
3  Audi         100  1992                regular unleaded       172   
4  FIAT  124 Spider  2017  premium unleaded (recommended)       160   

  Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                6            MANUAL   rear wheel drive                2   
1                6            MANUAL   rear wheel drive                2   
2                6            MANUAL   rear wheel drive                2   
3                6            MANUAL  front wheel drive                4   
4                4            MANUAL   rear wheel drive                2   

                           Market Category Vehicle Size Vehicle Style  \
0  "Factory Tuner,Luxury,High-Performance"      Compact         Coupe   
1                     "Luxury,Performance"      Compact   Convertible   
2                "Luxury,High-Performance"      Compact         Coupe   
3                                   Luxury      Midsize         Sedan   
4                              Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           24        17        3105   2000  
4           35        26         819  27495

In [ ]:
df = pd.DataFrame(data)

In [77]:
df

Make       Model  Year                Engine Fuel Type Engine HP  \
0   BMW  1 Series M  2011     premium unleaded (required)       335   
1   BMW    1 Series  2011     premium unleaded (required)       300   
2   BMW    1 Series  2011     premium unleaded (required)       300   
3  Audi         100  1992                regular unleaded       172   
4  FIAT  124 Spider  2017  premium unleaded (recommended)       160   

  Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                6            MANUAL   rear wheel drive                2   
1                6            MANUAL   rear wheel drive                2   
2                6            MANUAL   rear wheel drive                2   
3                6            MANUAL  front wheel drive                4   
4                4            MANUAL   rear wheel drive                2   

                           Market Category Vehicle Size Vehicle Style  \
0  "Factory Tuner,Luxury,High-Performance"      Compact         Coupe   
1                     "Luxury,Performance"      Compact   Convertible   
2                "Luxury,High-Performance"      Compact         Coupe   
3                                   Luxury      Midsize         Sedan   
4                              Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           24        17        3105   2000  
4           35        26         819  27495

In [97]:
df[(df['Make'] == 'BMW')]

Make       Model  Year             Engine Fuel Type Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)       335   
1  BMW    1 Series  2011  premium unleaded (required)       300   
2  BMW    1 Series  2011  premium unleaded (required)       300   

  Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0                6            MANUAL  rear wheel drive                2   
1                6            MANUAL  rear wheel drive                2   
2                6            MANUAL  rear wheel drive                2   

                           Market Category Vehicle Size Vehicle Style  \
0  "Factory Tuner,Luxury,High-Performance"      Compact         Coupe   
1                     "Luxury,Performance"      Compact   Convertible   
2                "Luxury,High-Performance"      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350

4. Найдите среднюю стоимость автомобиля BMW и выведите данное значение с точность до двух знаком после запятой.

In [103]:
round(df['MSRP'].mean(), 2)

30526.0

5. Определите каких автомобилей больше с ручной коробокой передач или автоматической?

In [ ]:
if (df['Transmission Type'] == 'MANUAL').sum() > (df['Transmission Type'] == 'AUTOMATIC').sum(): print('MANUAL') else: print('AUTOMATIC')

SyntaxError: invalid syntax (<ipython-input-1-ce3c0690d3f4>, line 1)